export const FORMAT_COMMANDS: Record<string, string> = {
    bold: 'bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'strikeThrough',
    superscript: 'superscript',
    subscript: 'subscript',
    alignleft: 'justifyLeft',
    aligncenter: 'justifyCenter',
    alignright: 'justifyRight',
    alignjustify: 'justifyFull',
    bullist: 'insertUnorderedList',
    numlist: 'insertOrderedList',
    outdent: 'outdent',
    indent: 'indent',
    removeformat: 'removeFormat',
    undo: 'undo',
    redo: 'redo',
    selectall: 'selectAll',
};
