export const DEFAULT_COLORS = [
    '#000000',
    '#434343',
    '#666666',
    '#999999',
    '#b7b7b7',
    '#cccccc',
    '#d9d9d9',
    '#efefef',
    '#f3f3f3',
    '#ffffff',
    '#980000',
    '#ff0000',
    '#ff9900',
    '#ffff00',
    '#00ff00',
    '#00ffff',
    '#4a86e8',
    '#0000ff',
    '#9900ff',
    '#ff00ff',
    '#e6b8af',
    '#f4cccc',
    '#fce5cd',
    '#fff2cc',
    '#d9ead3',
    '#d0e0e3',
    '#c9daf8',
    '#cfe2f3',
    '#d9d2e9',
    '#ead1dc',
    '#dd7e6b',
    '#ea9999',
    '#f9cb9c',
    '#ffe599',
    '#b6d7a8',
    '#a2c4c9',
    '#a4c2f4',
    '#9fc5e8',
    '#b4a7d6',
    '#d5a6bd',
];
export const DEFAULT_FONT_FAMILIES = [
    'Arial',
    'Book Antiqua',
    'Comic Sans MS',
    'Courier New',
    'Georgia',
    'Helvetica',
    'Impact',
    'Symbol',
    'Tahoma',
    'Terminal',
    'Times New Roman',
    'Trebuchet MS',
    'Verdana',
].map((value) => ({ label: value, value }));
export const DEFAULT_FONT_SIZES = ['8pt', '10pt', '12pt', '14pt', '18pt', '24pt', '36pt'].map(
    (value) => ({ label: value, value }),
);
export const DEFAULT_LINE_HEIGHTS = ['1', '1.1', '1.2', '1.3', '1.4', '1.5', '1.75', '2'].map(
    (value) => ({ label: value, value }),
);
export const DEFAULT_BLOCKS = [
    { label: 'Paragraph', value: 'p' },
    { label: 'Heading 1', value: 'h1' },
    { label: 'Heading 2', value: 'h2' },
    { label: 'Heading 3', value: 'h3' },
    { label: 'Heading 4', value: 'h4' },
    { label: 'Heading 5', value: 'h5' },
    { label: 'Heading 6', value: 'h6' },
    { label: 'Preformatted', value: 'pre' },
    { label: 'Blockquote', value: 'blockquote' },
] as const;
export const DEFAULT_ALLOWED_TAGS = [
    'p',
    'br',
    'div',
    'span',
    'strong',
    'b',
    'em',
    'i',
    'u',
    's',
    'strike',
    'sup',
    'sub',
    'code',
    'pre',
    'blockquote',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'ul',
    'ol',
    'li',
    'a',
    'img',
    'figure',
    'figcaption',
    'table',
    'thead',
    'tbody',
    'tfoot',
    'tr',
    'th',
    'td',
    'caption',
    'hr',
    'video',
    'audio',
    'source',
    'iframe',
];
export const DEFAULT_ALLOWED_ATTRIBUTES: Record<string, string[]> = {
    '*': ['class', 'style', 'title', 'dir', 'id'],
    span: [
        'data-erag-mention',
        'data-erag-mention-id',
        'data-erag-mention-label',
        'data-erag-mention-value',
        'data-erag-merge-tag',
        'data-erag-merge-tag-value',
        'data-erag-merge-tag-label',
        'contenteditable',
    ],
    a: ['href', 'target', 'rel', 'name'],
    img: ['src', 'alt', 'width', 'height'],
    table: ['width', 'cellpadding', 'cellspacing', 'border'],
    td: ['colspan', 'rowspan', 'width', 'height'],
    th: ['colspan', 'rowspan', 'scope', 'width', 'height'],
    video: ['src', 'controls', 'width', 'height', 'poster'],
    audio: ['src', 'controls'],
    source: ['src', 'type'],
    iframe: ['src', 'width', 'height', 'allow', 'allowfullscreen', 'title'],
};
