import type { EmojiCategory, EmojiCategoryFilter, EmojiItem } from '../types';

export const EMOJI_CATEGORIES: readonly EmojiCategoryFilter[] = [
    'All',
    'Smileys & People',
    'Animals & Nature',
    'Food & Drink',
    'Activity',
    'Travel & Places',
    'Objects',
    'Symbols',
    'Flags',
];

export const EMOJIS: readonly EmojiItem[] = [
    { value: '😀', label: 'Grinning face', category: 'Smileys & People' },
    { value: '😃', label: 'Smiling face with big eyes', category: 'Smileys & People' },
    { value: '😄', label: 'Smiling face', category: 'Smileys & People' },
    { value: '😁', label: 'Beaming face', category: 'Smileys & People' },
    { value: '😂', label: 'Face with tears of joy', category: 'Smileys & People' },
    { value: '🤣', label: 'Rolling on the floor laughing', category: 'Smileys & People' },
    { value: '😊', label: 'Smiling face with smiling eyes', category: 'Smileys & People' },
    { value: '😍', label: 'Smiling face with heart eyes', category: 'Smileys & People' },
    { value: '🥳', label: 'Partying face', category: 'Smileys & People' },
    { value: '😎', label: 'Smiling face with sunglasses', category: 'Smileys & People' },
    { value: '🤔', label: 'Thinking face', category: 'Smileys & People' },
    { value: '😭', label: 'Loudly crying face', category: 'Smileys & People' },
    { value: '👍', label: 'Thumbs up', category: 'Smileys & People' },
    { value: '👏', label: 'Clapping hands', category: 'Smileys & People' },
    { value: '🙏', label: 'Folded hands', category: 'Smileys & People' },
    { value: '💪', label: 'Flexed biceps', category: 'Smileys & People' },
    { value: '🐶', label: 'Dog', category: 'Animals & Nature' },
    { value: '🐱', label: 'Cat', category: 'Animals & Nature' },
    { value: '🐭', label: 'Mouse', category: 'Animals & Nature' },
    { value: '🐰', label: 'Rabbit', category: 'Animals & Nature' },
    { value: '🦊', label: 'Fox', category: 'Animals & Nature' },
    { value: '🐻', label: 'Bear', category: 'Animals & Nature' },
    { value: '🐼', label: 'Panda', category: 'Animals & Nature' },
    { value: '🦁', label: 'Lion', category: 'Animals & Nature' },
    { value: '🐸', label: 'Frog', category: 'Animals & Nature' },
    { value: '🌸', label: 'Cherry blossom', category: 'Animals & Nature' },
    { value: '🌻', label: 'Sunflower', category: 'Animals & Nature' },
    { value: '🌳', label: 'Tree', category: 'Animals & Nature' },
    { value: '🍎', label: 'Red apple', category: 'Food & Drink' },
    { value: '🍌', label: 'Banana', category: 'Food & Drink' },
    { value: '🍇', label: 'Grapes', category: 'Food & Drink' },
    { value: '🍉', label: 'Watermelon', category: 'Food & Drink' },
    { value: '🍕', label: 'Pizza', category: 'Food & Drink' },
    { value: '🍔', label: 'Hamburger', category: 'Food & Drink' },
    { value: '🍟', label: 'French fries', category: 'Food & Drink' },
    { value: '🍰', label: 'Cake', category: 'Food & Drink' },
    { value: '☕', label: 'Hot beverage', category: 'Food & Drink' },
    { value: '🥤', label: 'Cup with straw', category: 'Food & Drink' },
    { value: '⚽', label: 'Soccer ball', category: 'Activity' },
    { value: '🏀', label: 'Basketball', category: 'Activity' },
    { value: '🏏', label: 'Cricket game', category: 'Activity' },
    { value: '🎾', label: 'Tennis', category: 'Activity' },
    { value: '🏆', label: 'Trophy', category: 'Activity' },
    { value: '🎯', label: 'Bullseye', category: 'Activity' },
    { value: '🎮', label: 'Video game', category: 'Activity' },
    { value: '🎨', label: 'Artist palette', category: 'Activity' },
    { value: '🚗', label: 'Car', category: 'Travel & Places' },
    { value: '🚌', label: 'Bus', category: 'Travel & Places' },
    { value: '🚆', label: 'Train', category: 'Travel & Places' },
    { value: '✈️', label: 'Airplane', category: 'Travel & Places' },
    { value: '🚀', label: 'Rocket', category: 'Travel & Places' },
    { value: '🏠', label: 'House', category: 'Travel & Places' },
    { value: '🏖️', label: 'Beach', category: 'Travel & Places' },
    { value: '🌍', label: 'Globe', category: 'Travel & Places' },
    { value: '💡', label: 'Light bulb', category: 'Objects' },
    { value: '📱', label: 'Mobile phone', category: 'Objects' },
    { value: '💻', label: 'Laptop', category: 'Objects' },
    { value: '⌨️', label: 'Keyboard', category: 'Objects' },
    { value: '📷', label: 'Camera', category: 'Objects' },
    { value: '🎁', label: 'Wrapped gift', category: 'Objects' },
    { value: '📌', label: 'Pushpin', category: 'Objects' },
    { value: '🔔', label: 'Bell', category: 'Objects' },
    { value: '❤️', label: 'Red heart', category: 'Symbols' },
    { value: '💯', label: 'Hundred points', category: 'Symbols' },
    { value: '✅', label: 'Check mark button', category: 'Symbols' },
    { value: '❌', label: 'Cross mark', category: 'Symbols' },
    { value: '⚠️', label: 'Warning', category: 'Symbols' },
    { value: '⭐', label: 'Star', category: 'Symbols' },
    { value: '🔥', label: 'Fire', category: 'Symbols' },
    { value: '✨', label: 'Sparkles', category: 'Symbols' },
    { value: '🇮🇳', label: 'Flag India', category: 'Flags' },
    { value: '🇺🇸', label: 'Flag United States', category: 'Flags' },
    { value: '🇬🇧', label: 'Flag United Kingdom', category: 'Flags' },
    { value: '🇨🇦', label: 'Flag Canada', category: 'Flags' },
    { value: '🇦🇺', label: 'Flag Australia', category: 'Flags' },
    { value: '🇯🇵', label: 'Flag Japan', category: 'Flags' },
    { value: '🇩🇪', label: 'Flag Germany', category: 'Flags' },
    { value: '🇫🇷', label: 'Flag France', category: 'Flags' },
    ...createEmojiItems('Smileys & People', [
        ['🙂', 'Slightly smiling face'],
        ['🙃', 'Upside down face'],
        ['😉', 'Winking face'],
        ['😇', 'Smiling face with halo'],
        ['🥰', 'Smiling face with hearts'],
        ['😘', 'Face blowing a kiss'],
        ['😋', 'Face savoring food'],
        ['😜', 'Winking face with tongue'],
        ['🤪', 'Zany face'],
        ['🤨', 'Face with raised eyebrow'],
        ['🧐', 'Face with monocle'],
        ['🤓', 'Nerd face'],
        ['🥸', 'Disguised face'],
        ['🤩', 'Star struck'],
        ['😏', 'Smirking face'],
        ['😒', 'Unamused face'],
        ['😔', 'Pensive face'],
        ['😢', 'Crying face'],
        ['😤', 'Face with steam from nose'],
        ['😡', 'Enraged face'],
        ['🤯', 'Exploding head'],
        ['😱', 'Face screaming in fear'],
        ['😳', 'Flushed face'],
        ['🥺', 'Pleading face'],
        ['😴', 'Sleeping face'],
        ['🤒', 'Face with thermometer'],
        ['🤢', 'Nauseated face'],
        ['🤠', 'Cowboy hat face'],
        ['🤡', 'Clown face'],
        ['👋', 'Waving hand'],
        ['👌', 'OK hand'],
        ['✌️', 'Victory hand'],
        ['🤞', 'Crossed fingers'],
        ['🤝', 'Handshake'],
        ['🙌', 'Raising hands'],
        ['🫶', 'Heart hands'],
        ['👀', 'Eyes'],
        ['🧠', 'Brain'],
        ['👶', 'Baby'],
        ['👩', 'Woman'],
        ['👨', 'Man'],
        ['🧑‍💻', 'Technologist'],
        ['👩‍🎨', 'Woman artist'],
        ['👨‍🚀', 'Man astronaut'],
        ['👨‍👩‍👧‍👦', 'Family'],
    ]),
    ...createEmojiItems('Animals & Nature', [
        ['🐯', 'Tiger'],
        ['🐨', 'Koala'],
        ['🐮', 'Cow'],
        ['🐷', 'Pig'],
        ['🐵', 'Monkey'],
        ['🙈', 'See no evil monkey'],
        ['🙉', 'Hear no evil monkey'],
        ['🙊', 'Speak no evil monkey'],
        ['🐔', 'Chicken'],
        ['🐧', 'Penguin'],
        ['🐦', 'Bird'],
        ['🦄', 'Unicorn'],
        ['🐝', 'Honeybee'],
        ['🦋', 'Butterfly'],
        ['🐌', 'Snail'],
        ['🐞', 'Lady beetle'],
        ['🐢', 'Turtle'],
        ['🐍', 'Snake'],
        ['🦎', 'Lizard'],
        ['🐙', 'Octopus'],
        ['🦀', 'Crab'],
        ['🐬', 'Dolphin'],
        ['🐳', 'Whale'],
        ['🦈', 'Shark'],
        ['🐘', 'Elephant'],
        ['🦒', 'Giraffe'],
        ['🌹', 'Rose'],
        ['🌺', 'Hibiscus'],
        ['🌷', 'Tulip'],
        ['🌱', 'Seedling'],
        ['🍀', 'Four leaf clover'],
        ['🍁', 'Maple leaf'],
        ['🌵', 'Cactus'],
        ['🌴', 'Palm tree'],
        ['🌈', 'Rainbow'],
        ['☀️', 'Sun'],
        ['🌙', 'Crescent moon'],
        ['❄️', 'Snowflake'],
    ]),
    ...createEmojiItems('Food & Drink', [
        ['🍏', 'Green apple'],
        ['🍐', 'Pear'],
        ['🍊', 'Tangerine'],
        ['🍋', 'Lemon'],
        ['🍓', 'Strawberry'],
        ['🫐', 'Blueberries'],
        ['🍒', 'Cherries'],
        ['🥭', 'Mango'],
        ['🍍', 'Pineapple'],
        ['🥝', 'Kiwi fruit'],
        ['🍅', 'Tomato'],
        ['🥑', 'Avocado'],
        ['🥦', 'Broccoli'],
        ['🌽', 'Ear of corn'],
        ['🥕', 'Carrot'],
        ['🥐', 'Croissant'],
        ['🍞', 'Bread'],
        ['🧀', 'Cheese wedge'],
        ['🍳', 'Cooking egg'],
        ['🥞', 'Pancakes'],
        ['🌭', 'Hot dog'],
        ['🌮', 'Taco'],
        ['🍿', 'Popcorn'],
        ['🍣', 'Sushi'],
        ['🍜', 'Steaming bowl'],
        ['🍦', 'Soft ice cream'],
        ['🍩', 'Doughnut'],
        ['🍪', 'Cookie'],
        ['🎂', 'Birthday cake'],
        ['🍫', 'Chocolate bar'],
        ['🍬', 'Candy'],
        ['🍯', 'Honey pot'],
        ['🥛', 'Glass of milk'],
        ['🫖', 'Teapot'],
        ['🍺', 'Beer mug'],
        ['🍷', 'Wine glass'],
    ]),
    ...createEmojiItems('Activity', [
        ['🏈', 'American football'],
        ['⚾', 'Baseball'],
        ['🏐', 'Volleyball'],
        ['🏉', 'Rugby football'],
        ['🥏', 'Flying disc'],
        ['🎱', 'Pool eight ball'],
        ['🏓', 'Ping pong'],
        ['🏸', 'Badminton'],
        ['🥊', 'Boxing glove'],
        ['🥋', 'Martial arts uniform'],
        ['⛳', 'Flag in hole'],
        ['⛸️', 'Ice skate'],
        ['🎿', 'Skis'],
        ['🏋️', 'Weight lifting'],
        ['🚴', 'Cyclist'],
        ['🏃', 'Runner'],
        ['🎲', 'Game die'],
        ['♟️', 'Chess pawn'],
        ['🎭', 'Performing arts'],
        ['🎤', 'Microphone'],
        ['🎸', 'Guitar'],
        ['🎹', 'Musical keyboard'],
    ]),
    ...createEmojiItems('Travel & Places', [
        ['🚕', 'Taxi'],
        ['🚙', 'Sport utility vehicle'],
        ['🏎️', 'Racing car'],
        ['🚓', 'Police car'],
        ['🚑', 'Ambulance'],
        ['🚒', 'Fire engine'],
        ['🚲', 'Bicycle'],
        ['🏍️', 'Motorcycle'],
        ['🚂', 'Locomotive'],
        ['🚇', 'Metro'],
        ['🚁', 'Helicopter'],
        ['🛸', 'Flying saucer'],
        ['⛵', 'Sailboat'],
        ['🚢', 'Ship'],
        ['⛽', 'Fuel pump'],
        ['🚦', 'Traffic light'],
        ['🗺️', 'World map'],
        ['🗽', 'Statue of Liberty'],
        ['🗼', 'Tokyo tower'],
        ['🏰', 'Castle'],
        ['🏯', 'Japanese castle'],
        ['🏟️', 'Stadium'],
        ['⛺', 'Tent'],
        ['🌋', 'Volcano'],
        ['🏔️', 'Snow capped mountain'],
        ['🌅', 'Sunrise'],
        ['🌃', 'Night with stars'],
    ]),
    ...createEmojiItems('Objects', [
        ['🖥️', 'Desktop computer'],
        ['🖨️', 'Printer'],
        ['🖱️', 'Computer mouse'],
        ['💾', 'Floppy disk'],
        ['💿', 'Optical disk'],
        ['🎥', 'Movie camera'],
        ['📺', 'Television'],
        ['📻', 'Radio'],
        ['🎧', 'Headphone'],
        ['🔋', 'Battery'],
        ['🔌', 'Electric plug'],
        ['⌚', 'Watch'],
        ['⏰', 'Alarm clock'],
        ['📚', 'Books'],
        ['📖', 'Open book'],
        ['📝', 'Memo'],
        ['✏️', 'Pencil'],
        ['📎', 'Paperclip'],
        ['📁', 'File folder'],
        ['📅', 'Calendar'],
        ['📦', 'Package'],
        ['✉️', 'Envelope'],
        ['🔒', 'Locked'],
        ['🔑', 'Key'],
        ['🔨', 'Hammer'],
        ['🧰', 'Toolbox'],
        ['🧲', 'Magnet'],
        ['🧪', 'Test tube'],
        ['💊', 'Pill'],
        ['🪥', 'Toothbrush'],
        ['🛒', 'Shopping cart'],
        ['💰', 'Money bag'],
        ['💎', 'Gem stone'],
    ]),
    ...createEmojiItems('Symbols', [
        ['🧡', 'Orange heart'],
        ['💛', 'Yellow heart'],
        ['💚', 'Green heart'],
        ['💙', 'Blue heart'],
        ['💜', 'Purple heart'],
        ['🖤', 'Black heart'],
        ['🤍', 'White heart'],
        ['💔', 'Broken heart'],
        ['💕', 'Two hearts'],
        ['💖', 'Sparkling heart'],
        ['💥', 'Collision'],
        ['💫', 'Dizzy'],
        ['💦', 'Sweat droplets'],
        ['💨', 'Dashing away'],
        ['➕', 'Plus'],
        ['➖', 'Minus'],
        ['➗', 'Divide'],
        ['♾️', 'Infinity'],
        ['❓', 'Question mark'],
        ['❗', 'Exclamation mark'],
        ['⭕', 'Hollow red circle'],
        ['🔴', 'Red circle'],
        ['🟠', 'Orange circle'],
        ['🟡', 'Yellow circle'],
        ['🟢', 'Green circle'],
        ['🔵', 'Blue circle'],
        ['🟣', 'Purple circle'],
        ['⬆️', 'Up arrow'],
        ['➡️', 'Right arrow'],
        ['⬇️', 'Down arrow'],
        ['⬅️', 'Left arrow'],
        ['🔄', 'Counterclockwise arrows'],
        ['▶️', 'Play button'],
        ['⏸️', 'Pause button'],
        ['ℹ️', 'Information'],
    ]),
    ...createEmojiItems('Flags', [
        ['🇧🇷', 'Flag Brazil'],
        ['🇲🇽', 'Flag Mexico'],
        ['🇦🇷', 'Flag Argentina'],
        ['🇪🇸', 'Flag Spain'],
        ['🇮🇹', 'Flag Italy'],
        ['🇵🇹', 'Flag Portugal'],
        ['🇳🇱', 'Flag Netherlands'],
        ['🇧🇪', 'Flag Belgium'],
        ['🇨🇭', 'Flag Switzerland'],
        ['🇸🇪', 'Flag Sweden'],
        ['🇳🇴', 'Flag Norway'],
        ['🇩🇰', 'Flag Denmark'],
        ['🇫🇮', 'Flag Finland'],
        ['🇮🇪', 'Flag Ireland'],
        ['🇵🇱', 'Flag Poland'],
        ['🇺🇦', 'Flag Ukraine'],
        ['🇷🇺', 'Flag Russia'],
        ['🇨🇳', 'Flag China'],
        ['🇰🇷', 'Flag South Korea'],
        ['🇸🇬', 'Flag Singapore'],
        ['🇮🇩', 'Flag Indonesia'],
        ['🇲🇾', 'Flag Malaysia'],
        ['🇹🇭', 'Flag Thailand'],
        ['🇦🇪', 'Flag United Arab Emirates'],
        ['🇸🇦', 'Flag Saudi Arabia'],
        ['🇿🇦', 'Flag South Africa'],
        ['🇳🇿', 'Flag New Zealand'],
        ['🇳🇵', 'Flag Nepal'],
        ['🇧🇩', 'Flag Bangladesh'],
        ['🇱🇰', 'Flag Sri Lanka'],
    ]),
];

function createEmojiItems(
    category: EmojiCategory,
    items: readonly (readonly [value: string, label: string])[],
): EmojiItem[] {
    return items.map(([value, label]) => ({ value, label, category }));
}
