import {
    DEFAULT_ALLOWED_ATTRIBUTES,
    DEFAULT_ALLOWED_TAGS,
    DEFAULT_BLOCKS,
    DEFAULT_COLORS,
    DEFAULT_FONT_FAMILIES,
    DEFAULT_FONT_SIZES,
    DEFAULT_LINE_HEIGHTS,
} from '../constants/editorDefaults';
import type { ResolvedEditorInit } from '../types';
import { normalizeMentionConfig } from './mentionConfig';
import { normalizeMergeTagConfig } from './mergeTagConfig';
import { normalizeEditorTemplatesConfig } from './templateConfig';

export const defaultEditorConfig: ResolvedEditorInit = {
    height: 420,
    minHeight: 240,
    placeholder: 'Write something...',
    menubar: true,
    toolbar: true,
    statusbar: true,
    branding: false,
    promotion: false,
    resize: true,
    readonly: false,
    autofocus: false,
    spellcheck: true,
    direction: 'ltr',
    contentStyle: '',
    contentClass: '',
    fontFamilyFormats: DEFAULT_FONT_FAMILIES,
    fontSizeFormats: DEFAULT_FONT_SIZES,
    lineHeightFormats: DEFAULT_LINE_HEIGHTS,
    blockFormats: [...DEFAULT_BLOCKS],
    textColors: DEFAULT_COLORS,
    backgroundColors: DEFAULT_COLORS,
    plugins: [
        'history',
        'formatting',
        'lists',
        'link',
        'image',
        'media',
        'table',
        'code',
        'preview',
        'fullscreen',
        'find-replace',
        'special-character',
        'emoji',
        'horizontal-rule',
        'anchor',
        'merge-tags',
        'templates',
        'date-time',
    ],
    acceptedFormats: ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
    maxImageSize: 5 * 1024 * 1024,
    uploadFieldName: 'file',
    uploadHeaders: {},
    uploadCredentials: 'same-origin',
    automaticUploads: true,
    pasteImages: true,
    imageFilePicker: true,
    imageUrlInput: true,
    imageResize: true,
    imageDefaultWidth: 320,
    sanitize: true,
    allowedTags: DEFAULT_ALLOWED_TAGS,
    allowedAttributes: DEFAULT_ALLOWED_ATTRIBUTES,
    relativeUrls: true,
    removeScriptHost: false,
    convertUrls: true,
    dateFormats: [
        {
            label: 'ISO date',
            type: 'date',
            format: 'iso-date',
            options: { year: 'numeric', month: '2-digit', day: '2-digit' },
        },
        {
            label: 'Local numeric date',
            type: 'date',
            options: { year: 'numeric', month: '2-digit', day: '2-digit' },
        },
        {
            label: 'Long date',
            type: 'date',
            options: { year: 'numeric', month: 'long', day: 'numeric' },
        },
    ],
    timeFormats: [
        {
            label: 'Current 24-hour time',
            type: 'time',
            options: { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false },
        },
        {
            label: 'Current 12-hour time',
            type: 'time',
            options: { hour: 'numeric', minute: '2-digit', second: '2-digit', hour12: true },
        },
    ],
    tableGridSize: 10,
    helpShortcutText: 'Press Alt+0 for help',
    mentions: normalizeMentionConfig(false),
    mergeTags: normalizeMergeTagConfig(false),
    templates: normalizeEditorTemplatesConfig(false),
};
